name : androidbuild

on:
   pull_request:
     branches : [master]

   push:
     branches : [master]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4.0.1

      - name: setupjdk
        uses: actions/setup-java@v3

        with:
          java-version: "17"
          distribution: 'adopt'

      - name: build with gradle
        run : ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.6

        with:
          name: one.apk
          path: app/build/outputs/apk/debug/app-debug.apk







